//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Input/Player Input Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Input Actions"",
    ""maps"": [
        {
            ""name"": ""Player General Inputs"",
            ""id"": ""55dedc6c-89fe-4b05-bd9d-d62b2bef30a3"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""fb33cecf-47ba-4af5-9c20-4e360e7157e2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""c813d559-44f5-48f1-9530-3c47259a9f10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""0a2fabb8-f637-4a21-8561-be2505ddb4c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use Tool"",
                    ""type"": ""Button"",
                    ""id"": ""feb231eb-2c0a-4767-9f37-568d5f636998"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Invetory"",
                    ""type"": ""Button"",
                    ""id"": ""bef3db52-2559-4281-86e2-2e6db63a268d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""Button"",
                    ""id"": ""3250b800-5c4d-4eb2-836e-4936e6b9ff09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cycle Tools Up"",
                    ""type"": ""Button"",
                    ""id"": ""5b94d89f-e5e1-4892-b48e-381109e9c3ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cycle Tools Down"",
                    ""type"": ""Button"",
                    ""id"": ""353e3208-59b9-4bbb-8713-8b91cb3aa20b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cycle Items Up"",
                    ""type"": ""Button"",
                    ""id"": ""1bb86fad-62af-4207-9fa0-af50801aa7c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cycle Items Down"",
                    ""type"": ""Button"",
                    ""id"": ""f56cfdf6-ed18-41b9-b523-d4409c361bab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Advance Day"",
                    ""type"": ""Button"",
                    ""id"": ""e91807a2-23c3-4824-b786-2b5eb8c662cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4ecd02c2-ab95-4377-86d9-6b3e78f88c15"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""826cc16c-9f64-4123-be94-b0c9fdcdc3b6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cb183f04-80e0-411c-989a-02b717953022"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5ffff7e5-f6da-47ce-afda-4a930da25376"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2785be4b-022c-4d46-95ee-7ead10b8d435"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f2b4787e-04c8-4fe8-b2d8-22ac48b78aed"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fcc7d54-2106-4ebf-b7f3-97e9e73e9160"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1673dbb4-f71f-4552-b040-192f61dfd4e4"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Invetory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7ae2e84-574b-4cac-9f19-c3675fa2a266"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""631db12a-2ec8-421c-9256-5cf339eeb12f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cycle Tools Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1f02f9c-da1d-4ea1-b238-9399e83e0853"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cycle Tools Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45f42d5f-5080-417a-82a9-f940fb7863a5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cycle Items Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba8c94c9-d604-4504-ab8f-9fa59de739ae"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cycle Items Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15e7e57b-f930-4065-9e38-9edee65569e4"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Tool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60cc3c57-7e35-49e3-8ce7-8faa5b304b0d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Advance Day"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player General Inputs
        m_PlayerGeneralInputs = asset.FindActionMap("Player General Inputs", throwIfNotFound: true);
        m_PlayerGeneralInputs_Movement = m_PlayerGeneralInputs.FindAction("Movement", throwIfNotFound: true);
        m_PlayerGeneralInputs_Cancel = m_PlayerGeneralInputs.FindAction("Cancel", throwIfNotFound: true);
        m_PlayerGeneralInputs_Interact = m_PlayerGeneralInputs.FindAction("Interact", throwIfNotFound: true);
        m_PlayerGeneralInputs_UseTool = m_PlayerGeneralInputs.FindAction("Use Tool", throwIfNotFound: true);
        m_PlayerGeneralInputs_Invetory = m_PlayerGeneralInputs.FindAction("Invetory", throwIfNotFound: true);
        m_PlayerGeneralInputs_Walk = m_PlayerGeneralInputs.FindAction("Walk", throwIfNotFound: true);
        m_PlayerGeneralInputs_CycleToolsUp = m_PlayerGeneralInputs.FindAction("Cycle Tools Up", throwIfNotFound: true);
        m_PlayerGeneralInputs_CycleToolsDown = m_PlayerGeneralInputs.FindAction("Cycle Tools Down", throwIfNotFound: true);
        m_PlayerGeneralInputs_CycleItemsUp = m_PlayerGeneralInputs.FindAction("Cycle Items Up", throwIfNotFound: true);
        m_PlayerGeneralInputs_CycleItemsDown = m_PlayerGeneralInputs.FindAction("Cycle Items Down", throwIfNotFound: true);
        m_PlayerGeneralInputs_AdvanceDay = m_PlayerGeneralInputs.FindAction("Advance Day", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player General Inputs
    private readonly InputActionMap m_PlayerGeneralInputs;
    private IPlayerGeneralInputsActions m_PlayerGeneralInputsActionsCallbackInterface;
    private readonly InputAction m_PlayerGeneralInputs_Movement;
    private readonly InputAction m_PlayerGeneralInputs_Cancel;
    private readonly InputAction m_PlayerGeneralInputs_Interact;
    private readonly InputAction m_PlayerGeneralInputs_UseTool;
    private readonly InputAction m_PlayerGeneralInputs_Invetory;
    private readonly InputAction m_PlayerGeneralInputs_Walk;
    private readonly InputAction m_PlayerGeneralInputs_CycleToolsUp;
    private readonly InputAction m_PlayerGeneralInputs_CycleToolsDown;
    private readonly InputAction m_PlayerGeneralInputs_CycleItemsUp;
    private readonly InputAction m_PlayerGeneralInputs_CycleItemsDown;
    private readonly InputAction m_PlayerGeneralInputs_AdvanceDay;
    public struct PlayerGeneralInputsActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerGeneralInputsActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerGeneralInputs_Movement;
        public InputAction @Cancel => m_Wrapper.m_PlayerGeneralInputs_Cancel;
        public InputAction @Interact => m_Wrapper.m_PlayerGeneralInputs_Interact;
        public InputAction @UseTool => m_Wrapper.m_PlayerGeneralInputs_UseTool;
        public InputAction @Invetory => m_Wrapper.m_PlayerGeneralInputs_Invetory;
        public InputAction @Walk => m_Wrapper.m_PlayerGeneralInputs_Walk;
        public InputAction @CycleToolsUp => m_Wrapper.m_PlayerGeneralInputs_CycleToolsUp;
        public InputAction @CycleToolsDown => m_Wrapper.m_PlayerGeneralInputs_CycleToolsDown;
        public InputAction @CycleItemsUp => m_Wrapper.m_PlayerGeneralInputs_CycleItemsUp;
        public InputAction @CycleItemsDown => m_Wrapper.m_PlayerGeneralInputs_CycleItemsDown;
        public InputAction @AdvanceDay => m_Wrapper.m_PlayerGeneralInputs_AdvanceDay;
        public InputActionMap Get() { return m_Wrapper.m_PlayerGeneralInputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerGeneralInputsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerGeneralInputsActions instance)
        {
            if (m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnMovement;
                @Cancel.started -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCancel;
                @Interact.started -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnInteract;
                @UseTool.started -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnUseTool;
                @UseTool.performed -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnUseTool;
                @UseTool.canceled -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnUseTool;
                @Invetory.started -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnInvetory;
                @Invetory.performed -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnInvetory;
                @Invetory.canceled -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnInvetory;
                @Walk.started -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnWalk;
                @CycleToolsUp.started -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleToolsUp;
                @CycleToolsUp.performed -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleToolsUp;
                @CycleToolsUp.canceled -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleToolsUp;
                @CycleToolsDown.started -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleToolsDown;
                @CycleToolsDown.performed -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleToolsDown;
                @CycleToolsDown.canceled -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleToolsDown;
                @CycleItemsUp.started -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleItemsUp;
                @CycleItemsUp.performed -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleItemsUp;
                @CycleItemsUp.canceled -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleItemsUp;
                @CycleItemsDown.started -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleItemsDown;
                @CycleItemsDown.performed -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleItemsDown;
                @CycleItemsDown.canceled -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnCycleItemsDown;
                @AdvanceDay.started -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnAdvanceDay;
                @AdvanceDay.performed -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnAdvanceDay;
                @AdvanceDay.canceled -= m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface.OnAdvanceDay;
            }
            m_Wrapper.m_PlayerGeneralInputsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @UseTool.started += instance.OnUseTool;
                @UseTool.performed += instance.OnUseTool;
                @UseTool.canceled += instance.OnUseTool;
                @Invetory.started += instance.OnInvetory;
                @Invetory.performed += instance.OnInvetory;
                @Invetory.canceled += instance.OnInvetory;
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @CycleToolsUp.started += instance.OnCycleToolsUp;
                @CycleToolsUp.performed += instance.OnCycleToolsUp;
                @CycleToolsUp.canceled += instance.OnCycleToolsUp;
                @CycleToolsDown.started += instance.OnCycleToolsDown;
                @CycleToolsDown.performed += instance.OnCycleToolsDown;
                @CycleToolsDown.canceled += instance.OnCycleToolsDown;
                @CycleItemsUp.started += instance.OnCycleItemsUp;
                @CycleItemsUp.performed += instance.OnCycleItemsUp;
                @CycleItemsUp.canceled += instance.OnCycleItemsUp;
                @CycleItemsDown.started += instance.OnCycleItemsDown;
                @CycleItemsDown.performed += instance.OnCycleItemsDown;
                @CycleItemsDown.canceled += instance.OnCycleItemsDown;
                @AdvanceDay.started += instance.OnAdvanceDay;
                @AdvanceDay.performed += instance.OnAdvanceDay;
                @AdvanceDay.canceled += instance.OnAdvanceDay;
            }
        }
    }
    public PlayerGeneralInputsActions @PlayerGeneralInputs => new PlayerGeneralInputsActions(this);
    public interface IPlayerGeneralInputsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnUseTool(InputAction.CallbackContext context);
        void OnInvetory(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnCycleToolsUp(InputAction.CallbackContext context);
        void OnCycleToolsDown(InputAction.CallbackContext context);
        void OnCycleItemsUp(InputAction.CallbackContext context);
        void OnCycleItemsDown(InputAction.CallbackContext context);
        void OnAdvanceDay(InputAction.CallbackContext context);
    }
}
